CREATE TABLE user (
    id BIGINT PRIMARY KEY IDENTITY,
    walletId BIGINT,
    name VARCHAR(150) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (walletId) REFERENCES wallet(id)
    INDEX idx_user_name (name)
    INDEX idx_walletId (walletId)
);

CREATE TABLE wallet (
    id BIGINT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    INDEX idx_wallet_name (name)
);

CREATE TABLE transaction (
    id BIGINT PRIMARY KEY IDENTITY,
    walletId BIGINT,
    balance DECIMAL(15,2) NOT NULL,
    orderType VARCHAR(25) NOT NULL,
    orderValue DECIMAL(15,2) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (walletId) REFERENCES wallet(id) ON DELETE CASCADE
    INDEX idx_walletId (walletId)
    INDEX idx_createdAt (createdAt)
);